### ISSUE TITLE
Random corruptions causing scheduler to fail

### ISSUE THREAD

**Issue by dioptre** [imranmomin/Hangfire.AzureCosmosDb#33]
I see this in the logs, and now find that schedules are failing indeterminately.
```
Error:
System.Collections.Generic.KeyNotFoundException: The given key 'Cron' was not present in the dictionary.
   at Hangfire.Storage.StorageConnectionExtensions.GetRecurringJobDtos(IStorageConnection connection, IEnumerable`1 ids)
   at Hangfire.Storage.StorageConnectionExtensions.GetRecurringJobs(IStorageConnection connection, IEnumerable`1 ids)
```

**Comment by imranmomin** [comment]
@dioptre - have been working on the fix. Will soon do a release. 

If you can pull `/patch_api_update` branch and test locally.
